#!/bin/bash

oldrev=`git rev-list --count HEAD | sed 's/[^[:digit:]]//g'`
newrev=`expr $oldrev + 1`
date=`date "+%Y-%m-%d %H:%M:%S"`

nano log

if [ -f log ]; then
  mv CHANGES.txt CHANGES2.txt
  echo '------------------------------------------------------------------------' > CHANGES.txt
  echo r$newrev '|' $USER '|' $date >> CHANGES.txt
  echo >> CHANGES.txt
  echo "Changed paths:" >> CHANGES.txt
  git status --short|grep -v ?? >> CHANGES.txt
  echo >> CHANGES.txt
  cat log >> CHANGES.txt
  cat CHANGES2.txt >> CHANGES.txt
  rm CHANGES2.txt
  
  echo "Changed paths:" > log2
  git status --short|grep -v ?? >> log2
  echo  >> log2
  cat log >> log2
  echo  >> log2
  git commit -F log2
  git push
  git fetch
else
  echo "Put commit information in log"
fi