#!/bin/bash

oldrev=`svn info | grep 'Last Changed Rev'| cut -f2 -d':' | sed 's/[^[:digit:]]//g'`
newrev=`expr $oldrev + 1`
date=`date "+%Y-%m-%d %H:%M:%S"`

nano log

if [ -f log ]; then
  svn log -r 440:HEAD > CHANGES.txt

  echo >> CHANGES.txt
  echo "Changed paths:" > log2
  svn -q status >> CHANGES.txt
  cat log >> CHANGES.txt
  echo  >> CHANGES.txt
  echo '------------------------------------------------------------------------' >> CHANGES.txt
  echo r$newrev '|' $USER '|' $date >> CHANGES.txt

  echo "Changed paths:" > log2
  svn -q status >> log2
  echo  >> log2
  cat log >> log2
  echo  >> log2
  svn ci -F log2
  svn list -R | grep -v '/$' | xargs svn propset svn:keywords "Id Rev Date Author" 1>/dev/null
  svn update
else
  echo "Put commit information in log"
fi