#!/bin/sh
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

if [ $# -lt 4 ]; then
	echo "Usage $0 WM.mnc WM.obj Wmout.obj threshold [curv] [fwhm]"
	exit
fi

if [ $# -eq 5 ]; then
    curv=$5
else
    curv=0.05
fi

if [ $# -eq 6 ]; then
    fwhm=$6
else
    fwhm=0
fi

if [ "$fwhm" == "0" ]; then
    image=$1
else
    mincblur -3dfwhm $fwhm $fwhm $fwhm $1 /tmp/$$blur
    image=/tmp/$$blur_blur.mnc
fi

# parameters for deforming WM
th1=$4
step=".1 .1 15 0 $th1 $th1 n 0 0 0"

iters=250
model="-1 .5 avg -0.15 0.15"
CAT_DeformSurf $image none 0 0 0 $2 $3 none 0 1 $model $step $iters 0.01 0.0

iters=250
model="-1 .5 avg -$curv $curv"
CAT_DeformSurf $image none 0 0 0 $3 $3 none 0 1 $model $step $iters 0.01 0.0

if [ "$fwhm" != "0" ]; then
    rm $image
fi