#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

########################################################
# global parameters
########################################################

fwhm=4
removestr=''

########################################################
# run main
########################################################

main ()
{
  parse_args ${1+"$@"}
  Recon

  exit 0
}


########################################################
# Recon
########################################################
Recon ()
{
  if [ -n "$ARGV_list" ]
  then
	for i in $ARGV_list
	do
     bn=`basename $i|sed -e s,.obj,,g -e s,${removestr},,g`
     dn=`dirname $i`
	   echo calculating $bn
	   CAT_SeparatePolygons $i ${dn}/sep.${bn} 0
	   CAT_Surf2Sphere ${dn}/sep.${bn} ${dn}/sphere.${bn}
	   CAT_FixTopology -bw 512 -smooth ${dn}/sep.${bn} ${dn}/sphere.${bn} ${dn}/fixed.${bn}
	   if [ ! "$fwhm" == "0" ]; then
	   		CAT_BlurSurfHK ${dn}/fixed.${bn} ${dn}/smoothed.fixed.${bn} $fwhm
	   fi
	done
  else
	echo "No arguments given."
	echo
	usage
	echo "Use the --help option for more information."
	exit 1
  fi

}

########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
	optname="`echo $1 | sed 's,=.*,,'`"
	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
	case "$1" in
		--r* | -r*)
			exit_if_empty "$optname" "$optarg"
			removestr=$optarg
			;;
		--f* | -f*)
			optarg=`echo $optarg | sed 's,[^0-9],,g'`
			exit_if_empty "$optname" "$optarg"
			fwhm=$optarg
			;;
		-h | --help | -v | --version | -V)
			help
			exit 1
			;;
		-*)
			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
			;;
		*)
			ARGV_list="$ARGV_list $1"
			;;
	esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
	exit 1
  fi
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: CAT_Recon name [name2 name3 ... nameN] [-f=fwhm_in_mm] [-r=remove_str_from_outputname]
		
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:

USAGE:
     
OPTIONS:
	name.obj   - input obj-file(s)
	-f         - diffusion heat kernel smoothing defined in fwhm in mm
    
EXAMPLE:

INPUT:
    MNI obj-files

OUTPUT:
 
USED FUNCTIONS:
    CAT_Recon

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
