#!/bin/sh

if [ ! $# -eq 1 ]; then
	echo "Usage:  CAT_Obj2Neurolens name.obj"
	exit 0
fi

# check for Neurolens
found=`which nldo 2>/dev/null`
if [ "$found" == "" ]; then
	echo "Error: Neurolens not found"
	exit 0
fi

TMP=/tmp/lh.pial

CAT_SurfConvert $1 $TMP
open $TMP