name: Compile CAT12 mex-files

on:
  workflow_dispatch:

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}

jobs:
  build_matlab_standalone:
    name: Build CAT12 standalone
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # This actions compiles by default with the newest available matlab version
        version: ["R2023b"]
        os: ["ubuntu-latest"] # macos-13 has Intel architecture, macos-latest has Apple Silicon
        #os: ["ubuntu-latest", "macos-13", "macos-latest", "windows-latest"] # macos-13 has Intel architecture, macos-latest has Apple Silicon

    steps:
      - name: Set up MATLAB
        id: setup_matlab
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{matrix.version}}
          products: MATLAB_Compiler

      - name: Extract MATLAB version to file
        uses: matlab-actions/run-command@v2
        with:
          command: |
            fileID = fopen('matlab_release.txt', 'w')
            fprintf(fileID, matlabRelease.Release)
            fclose(fileID)
        # sometimes this step hangs when closing matlab, automatically terminating after 2 minutes solves the issue
        timeout-minutes: 2
        continue-on-error: true

      - name: Set environment variable with MATLAB version
        shell: bash # Works on Windows as well because of shell: bash
        run: |
          matlab_release=$(cat matlab_release.txt)
          echo "MATLAB_VERSION=$matlab_release" >> $GITHUB_ENV

      #- name: Checkout CAT
      #  uses: actions/checkout@v4

      - name: Compile CAT12 mex-files
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('spm');
            cd('spm/toolbox/cat12')
            compile
            cd('spm')
            
