name: Compile CAT12 mex-files

on:
  workflow_dispatch:

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}

jobs:
  test_compile:
    runs-on: ubuntu-22.04
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          
      - name: Checkout SPM
        uses: actions/checkout@v3
        with:
          repository: spm/spm
          path: spm

      - name: Compile CAT12 mex-files
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('spm');
            cd('spm/toolbox/cat12')
            compile
            cd('spm')
            
