name: Compile CAT12 mex-files

on:
  workflow_dispatch:

jobs:
  test_compile:
    name: Compile CAT12 mex-files
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-13", "macos-latest", "windows-latest"] # macos-13 has Intel architecture, macos-latest has Apple Silicon
        include: # These includes are just giving the OSs additional names
          - os: ubuntu-22.04
            os_name: Linux
            mex_name: mexa64
          - os: macos-13
            os_name: macOS_Intel
            mex_name: mexmaci64
          - os: macos-latest
            os_name: macOS_Arm64
            mex_name: mexmaca64
          - os: windows-latest
            os_name: Windows
            mex_name: mexw64
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          
      - name: Install rsync
        if: runner.os == 'Windows'
        run: choco install -y rsync

      - name: Checkout SPM
        uses: actions/checkout@v3
        with:
          repository: spm/spm
          path: spm

      - name: Install CAT12 in SPM toolbox
        shell: bash
        run: |
          mkdir -p spm/toolbox/cat12
          rsync -a --exclude='.git' \
            --exclude='spm/toolbox/cat12/' \
            --exclude='batches/' \
            --exclude='catQC/' \
            --exclude='check_pipeline/' \
            --exclude='development/' \
            --exclude='html/' \
            --exclude='internal/' \
            --exclude='mexmaca/' \
            --exclude='mexmaci/' \
            --exclude='spm/' \
            --exclude='Makefile' \
            ./ spm/toolbox/cat12/

      - name: Compile CAT12 mex-files
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('spm');
            cd('spm/toolbox/cat12')
            compile

      - name: Install zip on Windows
        if: runner.os == 'Windows'
        run: choco install zip -y
        shell: bash

      - name: Zip mex-files
        run: |
          cd spm/toolbox/
          zip -r ../../cat_${{ github.ref_name }}_${{ matrix.mex_name }}.zip . -i cat12/*.${{ matrix.mex_name }}

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: cat_${{ github.ref_name }}_${{ matrix.mex_name }}
          path: cat_*.zip


