name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: cat12

    steps:
    - uses: actions/checkout@v3
          
    - name: Run zip
      run: make zip
